import { NextResponse } from 'next/server';
import { type Clip } from '@/lib/projects';
import { listProjects, saveProject } from '@/lib/project-store';
import { getCurrentUser } from '@/lib/auth';
import { z } from 'zod';
const bodySchema=z.object({url:z.string().url(),prompt:z.string().trim().max(500).optional().default('')});
function workerUrl(){return process.env.WORKER_URL||'http://localhost:8080';}
export async function POST(req:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:'Sign in to create a project.'},{status:401});const parsed=bodySchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Enter a valid video URL.'},{status:400});const id=crypto.randomUUID();const createdAt=new Date().toISOString();const project={id,userId:user.id,sourceUrl:parsed.data.url,customPrompt:parsed.data.prompt,status:'queued' as const,progress:0,stage:'Queued',createdAt,clips:[] as Clip[]};await saveProject(project);try{const response=await fetch(`${workerUrl()}/process`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:parsed.data.url,prompt:parsed.data.prompt,out:process.env.WORKER_OUTPUT_DIR||'./output'}),cache:'no-store'});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Media worker failed to queue the project.');const queued={...project,jobId:result.jobId,status:'processing' as const,progress:2,stage:'Downloading source'};await saveProject(queued);return NextResponse.json(queued,{status:202});}catch(error){const failed={...project,status:'failed' as const,progress:100,stage:'Failed',error:error instanceof Error?error.message:'Could not reach media worker.'};await saveProject(failed);return NextResponse.json(failed,{status:502});}}
export async function GET(){const user=await getCurrentUser();if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});return NextResponse.json(await listProjects(50,user.id));}
