import { readFile } from 'node:fs/promises';
import { basename } from 'node:path';

export type PublishInput={platform:'youtube'|'tiktok'|'instagram';accessToken:string;filePath:string;title:string;description?:string;caption?:string;privacy?:string;accountId?:string;publicUrl?:string};
async function jsonOrThrow(res:Response){const text=await res.text();let data:any={};try{data=JSON.parse(text)}catch{}if(!res.ok)throw new Error(data?.error?.message||data?.error?.code||text||`Platform request failed (${res.status})`);return data;}
export async function publishVideo(input:PublishInput){if(input.platform==='youtube')return publishYouTube(input);if(input.platform==='tiktok')return publishTikTok(input);return publishInstagram(input);}
async function publishYouTube(i:PublishInput){const bytes=await readFile(i.filePath);const meta={snippet:{title:i.title.slice(0,100),description:(i.description||'').slice(0,5000),categoryId:'22'},status:{privacyStatus:i.privacy||'private',selfDeclaredMadeForKids:false}};const init=await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status',{method:'POST',headers:{Authorization:`Bearer ${i.accessToken}`,'Content-Type':'application/json; charset=UTF-8','X-Upload-Content-Type':'video/mp4','X-Upload-Content-Length':String(bytes.length)},body:JSON.stringify(meta)});const uploadUrl=init.headers.get('location');if(!uploadUrl)throw new Error('YouTube did not return an upload URL.');const uploaded=await fetch(uploadUrl,{method:'PUT',headers:{Authorization:`Bearer ${i.accessToken}`,'Content-Type':'video/mp4','Content-Length':String(bytes.length)},body:bytes});return jsonOrThrow(uploaded);}
async function publishTikTok(i:PublishInput){if(!i.publicUrl)throw new Error('TikTok PULL_FROM_URL publishing requires PUBLIC_MEDIA_BASE_URL and a public clip URL.');const res=await fetch('https://open.tiktokapis.com/v2/post/publish/video/init/',{method:'POST',headers:{Authorization:`Bearer ${i.accessToken}`,'Content-Type':'application/json; charset=UTF-8'},body:JSON.stringify({post_info:{title:(i.caption||i.title).slice(0,2200),privacy_level:i.privacy||'SELF_ONLY',disable_duet:false,disable_comment:false,disable_stitch:false,video_cover_timestamp_ms:1000},source_info:{source:'PULL_FROM_URL',video_url:i.publicUrl}})});return jsonOrThrow(res);}
async function publishInstagram(i:PublishInput){if(!i.accountId)throw new Error('Instagram publishing requires the Instagram professional account ID.');if(!i.publicUrl)throw new Error('Instagram Reels publishing requires a public clip URL.');const create=await fetch(`https://graph.facebook.com/v23.0/${encodeURIComponent(i.accountId)}/media`,{method:'POST',headers:{Authorization:`Bearer ${i.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({media_type:'REELS',video_url:i.publicUrl,caption:i.caption||i.title,share_to_feed:true})});const container=await jsonOrThrow(create);let status='IN_PROGRESS';for(let n=0;n<30&&status==='IN_PROGRESS';n++){await new Promise(r=>setTimeout(r,2000));const check=await fetch(`https://graph.facebook.com/v23.0/${container.id}?fields=status_code,status`,{headers:{Authorization:`Bearer ${i.accessToken}`}});const data=await jsonOrThrow(check);status=data.status_code||data.status||'IN_PROGRESS';if(status==='ERROR')throw new Error('Instagram media container failed.');}if(status!=='FINISHED')return {containerId:container.id,status};const publish=await fetch(`https://graph.facebook.com/v23.0/${encodeURIComponent(i.accountId)}/media_publish`,{method:'POST',headers:{Authorization:`Bearer ${i.accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({creation_id:container.id})});return jsonOrThrow(publish);}
export function publicClipUrl(filePath:string){const base=process.env.PUBLIC_MEDIA_BASE_URL?.replace(/\/$/,'');if(!base) return null;return `${base}/${encodeURIComponent(basename(filePath))}`;}
